import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";
import { queryClient } from "@/lib/tanstackQuery/queryClient";
//tanstack query
import { QueryClientProvider } from "@tanstack/react-query";
//react hot toast
import { Toaster } from "react-hot-toast";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <Toaster />
          {children}
        </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
