import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";

//tanstack query
import TanstackProvider from "@/components/providers/tanstack-provider";

//react hot toast
import { Toaster } from "react-hot-toast";



const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable}  antialiased`}
      >
       
          <AuthProvider>
            <Toaster />
       <TanstackProvider>{children}</TanstackProvider>
        </AuthProvider>
   
      </body>
    </html>
  );
}
